// How a reviewer reads one AI-image check (CHAPTER 108). No client imports, so
// the labels are testable without a browser.

export type AuthenticityStatus = "checked" | "unsupported" | "pending" | "unavailable";
export type AuthenticityVerdict = "real" | "fake" | "inpainting";

export type AuthenticityCheck = {
  bucket: string;
  storage_path: string;
  status: AuthenticityStatus;
  reason: string | null;
  verdict: AuthenticityVerdict | null;
  confidence: number | null;
  prob_real: number | null;
  prob_fake: number | null;
  prob_inpainting: number | null;
  checked_at: string;
};

export type AuthenticityTone = "ok" | "danger" | "warning" | "neutral" | "busy";

/** One line a reviewer can read at a glance, and the tone it is shown in. */
export const describeCheck = (
  check: AuthenticityCheck | undefined,
): { label: string; tone: AuthenticityTone; detail: string } => {
  if (!check) {
    return {
      label: "AI check not run",
      tone: "neutral",
      detail: "Press Run AI check above. Opening a review never spends credits on its own.",
    };
  }
  if (check.status === "checked") {
    const percent = check.confidence == null ? "" : ` · ${Math.round(check.confidence * 100)}%`;
    if (check.verdict === "fake") {
      return {
        label: `Likely AI-generated${percent}`,
        tone: "danger",
        detail: "The detector judged this whole image to be generated by AI.",
      };
    }
    if (check.verdict === "inpainting") {
      return {
        label: `Possible AI edit${percent}`,
        tone: "warning",
        detail: "The detector judged this a real photo with parts edited by AI - check names, dates, plate numbers and faces closely.",
      };
    }
    return {
      label: `No AI detected${percent}`,
      tone: "ok",
      detail: "The detector found no sign of AI generation or AI editing. Ordinary editing (such as retyped text) can still pass - read the document itself.",
    };
  }
  const known = REASON_LABELS[check.reason ?? ""];
  return {
    label: known?.label ?? "Not checked",
    tone: check.status === "pending" ? "busy" : "neutral",
    detail: known?.detail ?? "The AI image check could not run for this file.",
  };
};

const REASON_LABELS: Record<string, { label: string; detail: string }> = {
  pdf: { label: "Not checkable · PDF", detail: "The detector reads images only. Review this PDF by eye." },
  file_type: { label: "Not checkable · file type", detail: "The detector reads JPG, PNG, WebP, GIF, BMP and TIFF images only." },
  too_large: { label: "Not checkable · over 10 MB", detail: "The detector accepts images up to 10 MB." },
  invalid_image: { label: "Not checkable · unreadable", detail: "The detector could not open this image." },
  rejected_file: { label: "Not checkable", detail: "The detector refused this file." },
  rate_limited: { label: "Checking…", detail: "Waiting for the detector's per-minute limit. It continues on its own." },
  busy: { label: "Checking…", detail: "The detector is busy. It continues on its own." },
  trial_expired: {
    label: "Not checked · subscription expired",
    detail: "The Walter Writes API trial or subscription has expired. Renew it and press Check again.",
  },
  insufficient_credits: {
    label: "Not checked · out of credits",
    detail: "The Walter Writes API has no credits left. Top up and press Check again.",
  },
  credits_exhausted: {
    label: "Not checked · out of credits",
    detail: "This month's Walter Writes credits are used up. They reset next billing cycle, or top up and press Check again.",
  },
  key_invalid: { label: "Not checked · API key invalid", detail: "The WALTER_API_KEY in Vercel is invalid, inactive or expired." },
  key_missing_scope: { label: "Not checked · key lacks access", detail: "The Walter Writes API key does not include the image detector." },
  not_configured: { label: "Not checked · detector off", detail: "No WALTER_API_KEY is set on the server." },
  service_unavailable: { label: "Not checked · detector down", detail: "The Walter Writes detector did not respond. Press Check again later." },
  unexpected_response: { label: "Not checked · bad answer", detail: "The detector answered in a way SafeDrive does not recognise." },
  file_missing: { label: "Not checked · file missing", detail: "The stored file could not be read." },
};

/** The same check whichever bucket name a page happens to know the file by. */
export const indexChecks = (checks: AuthenticityCheck[]) =>
  Object.fromEntries(checks.map((check) => [check.storage_path, check])) as Record<string, AuthenticityCheck>;
